// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs5Y-NSDQX4j2E_UKBECz_wip_bpOcQ0s',
    appId: '1:403775489939:web:796f773b6bddf515100a66',
    messagingSenderId: '403775489939',
    projectId: 'uk-bhulekh-ios',
    authDomain: 'uk-bhulekh-ios.firebaseapp.com',
    storageBucket: 'uk-bhulekh-ios.appspot.com',
    measurementId: 'G-57ZW1HCLWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9MJ-C8p8FicPhpjvAWBJ-8juhE5kM8YM',
    appId: '1:403775489939:android:59ac9f7b34272162100a66',
    messagingSenderId: '403775489939',
    projectId: 'uk-bhulekh-ios',
    storageBucket: 'uk-bhulekh-ios.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb1xNP6SYipkHVypycvv9y7LZDV33UEwo',
    appId: '1:403775489939:ios:1da205d431fe94ec100a66',
    messagingSenderId: '403775489939',
    projectId: 'uk-bhulekh-ios',
    storageBucket: 'uk-bhulekh-ios.appspot.com',
    iosBundleId: 'com.clovenandworks.bhulekhUk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb1xNP6SYipkHVypycvv9y7LZDV33UEwo',
    appId: '1:403775489939:ios:afdf1cd0d984841d100a66',
    messagingSenderId: '403775489939',
    projectId: 'uk-bhulekh-ios',
    storageBucket: 'uk-bhulekh-ios.appspot.com',
    iosBundleId: 'com.clovenandworks.bhulekhUk.RunnerTests',
  );
}
